apiVersion: v1
kind: ConfigMap
metadata:
  name: stress-config
  namespace: dynamic-schedule-stress-test
  annotations:
    argocd.argoproj.io/sync-wave: "3"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
data:
  CPU_LOAD: "8"
  MEM_LOAD: "4"
  MEM_SIZE: "512M"

